Bring docs to the style guide.
iotaledger/inx-faucet pull request #42
Opened 2022-08-26 13:54 UTC by aleksei-korolev

2022-08-26 13:54 UTC, aleksei-korolev commented
@iotaledger/tech-writers

2022-08-26 14:12 UTC, lucas-tortora requested changes

2022-08-26 14:12 UTC, lucas-tortora commented on documentation/docs/welcome.md
> +The participation extension connects to the local Hornet instance by default.
What participation extension?

2022-08-26 14:12 UTC, lucas-tortora commented on documentation/docs/welcome.md
> +To run your own faucet you need to provide a private key containing funds to the faucet. To do this you must launch `inx-faucet` while passing a `FAUCET_PRV_KEY` environment variable that contains th
```suggestion
To run your own faucet, you need to provide a private key containing funds to the faucet. To do this, you must launch the `inx-faucet` while passing a `FAUCET_PRV_KEY` environment variable that contains the private key.
```

2022-08-26 14:12 UTC, lucas-tortora commented on documentation/docs/welcome.md
> +Faucets give tokens away. This is useful when you need to distribute tokens on a test network, or distribute tokens on a private Tangle. INX-Faucet extends your node with this functionality.
```suggestion
Faucets give tokens away. This is useful when you need to distribute tokens on a test network or distribute tokens on a private Tangle. The INX-Faucet plugin extends your node with this functionality.
```

2022-08-29 20:09 UTC, aleksei-korolev commented on documentation/docs/welcome.md
> +Faucets give tokens away. This is useful when you need to distribute tokens on a test network, or distribute tokens on a private Tangle. INX-Faucet extends your node with this functionality.
I've rewritten this paragraphs.

2023-08-30 18:21 UTC, closed without merging